# Generated by Django 5.0.6 on 2024-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystar', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
