# Generated by Django 5.0.6 on 2024-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystar', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='sitter_assigned_to',
            field=models.CharField(default='Any', max_length=100),
        ),
    ]
