# Generated by Django 5.0.6 on 2024-05-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystar', '0004_baby_sitter_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('dollsale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='daystar.dollsale')),
            ],
            bases=('daystar.dollsale',),
        ),
    ]
